version: '3.4'

services:

    # APP
    nginx:
        build: docker/nginx
        volumes:
            - ./:/symfony:cached
        links:
            - php
        depends_on:
            - php
        ports:
            - "8000:80"
        restart: always
    node:
        build: docker/node
        volumes:
            - ./:/app
        working_dir: /app
    php:
        build: docker/php
        volumes:
            - ./:/symfony:cached
